### ISSUE TITLE
Importing visualizer to project with no visualizer throws exception

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme-cli#180]
Basically it assumes there's a `Visualizers.json` and fails when trying to read it in.

```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\GIT\vulcan-embedding\src\visualizers\Visualizers.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at VisualizerManager._addToVisualizersJSON (C:\Users\pmeijer\AppData\Roaming\nvm\v5.10.1\node_modules\webgme-cli\lib\VisualizerManager.js:91:8)
    at C:\Users\pmeijer\AppData\Roaming\nvm\v5.10.1\node_modules\webgme-cli\lib\VisualizerManager.js:179:18
    at C:\Users\pmeijer\AppData\Roaming\nvm\v5.10.1\node_modules\webgme-cli\lib\ComponentManager.js:161:24
    at VisualizerManager._getJsonForConfig (C:\Users\pmeijer\AppData\Roaming\nvm\v5.10.1\node_modules\webgme-cli\lib\VisualizerManager.js:119:12)
    at ChildProcess.<anonymous> (C:\Users\pmeijer\AppData\Roaming\nvm\v5.10.1\node_modules\webgme-cli\lib\ComponentManager.js:147:18)
    at emitTwo (events.js:105:20)
    at ChildProcess.emit (events.js:185:7)
```

**Comment by brollb** [comment]
what version of webgme-cli are you using? This should have been fixed in #129
