### ISSUE TITLE
SyntaxError: Unexpected end of input when trying to run: webgme new plugin <pluginName>

### ISSUE THREAD

**Issue by finger563** [webgme/webgme-cli#198]
```
    at Object.parse (native)
    at Object.getConfig (/usr/lib/node_modules/webgme-cli/lib/utils.js:88:17)
    at PluginManager.ComponentManager._prepareWebGmeConfig (/usr/lib/node_modules/webgme-cli/lib/ComponentManager.js:287
:28)
    at PluginManager.ComponentManager (/usr/lib/node_modules/webgme-cli/lib/ComponentManager.js:28:10)
    at new PluginManager (/usr/lib/node_modules/webgme-cli/lib/PluginManager.js:27:22)
    at Command.<anonymous> (/usr/lib/node_modules/webgme-cli/bin/webgme-new-plugin:16:23)
    at Command.listener (/usr/lib/node_modules/webgme-cli/node_modules/commander/index.js:302:8)
    at emitOne (events.js:77:13)
    at Command.emit (events.js:169:7)
    at Command.parseArgs (/usr/lib/node_modules/webgme-cli/node_modules/commander/index.js:625:12)
```

**Comment by finger563** [comment]
additionally, the help text is incorrect, showing: `Usage: webgme-new-plugin [options] <pluginID>`

**Comment by brollb** [comment]
It looks like your `webgme-setup.json` is malformed. I should probably have a nice error message for it though...

Have you edited your webgme-setup.json by hand recently?

The usage message is a result of using git-style subcommands w/ commanderjs... I can look into making a PR onto that project or suggesting that it is changed because it is misleading.

**Comment by finger563** [comment]
Ah you're right, somehow one of the braces got deleted. (Shared project with other developers)
