### ISSUE TITLE
Error when invoking new decorator/visualizer: forEach undefined

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-cli#268]
**Environment:**

***webgme-cli version (`webgme -v`):***
v2.8.4
***Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)***
```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.15.0-112-generic
```
***NodeJS version (`node -v`):***

v8.11.4
***npm version (`npm -v`):***
6.4.0
**Description:**
When invoking new decorator/visualizer one gets error in the 'forEach'
**Steps to Reproduce:**
```
webgme new decorator MyNewDecorator --inherit
```
**Results:**

```
/home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/webgme-cli/src/utils.js:200
    array.forEach(function(key) {
          ^

TypeError: Cannot read property 'forEach' of undefined
    at unique (/home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/webgme-cli/src/utils.js:200:11)
    at /home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/webgme-cli/src/utils.js:221:20
    at Array.map (<anonymous>)
    at /home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/webgme-cli/src/utils.js:219:35
    at Array.forEach (<anonymous>)
    at getWebGMEConfigContent (/home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/webgme-cli/src/utils.js:218:38)
    at Object.updateWebGMEConfig (/home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/webgme-cli/src/utils.js:138:19)
    at DecoratorManager.ComponentManager._register (/home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/webgme-cli/src/ComponentManager.js:327:11)
    at /home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/webgme-cli/src/DecoratorManager.js:75:14
    at /home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/webgme-cli/src/shim/DecoratorGenerator.js:44:9
```

**Comment by yogeshVU** [comment]
I think there maybe an error the way I had setup the project. So perhaps this was a result of that project import. I tried to create a new webgme-cli project and invoke the new decorator/visualizer, it worked without any errors. So closing this ticket.

**Comment by brollb** [comment]
Sounds good. Feel free to reopen if it shows up again :)
