### ISSUE TITLE
webgme start error 

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-cli#272]
**Environment:**
ubuntu 18.04

***webgme-cli version (`webgme -v`):***
v2.8.4

***Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)***
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
***NodeJS version (`node -v`):***
v12.19.0
***npm version (`npm -v`):***
6.14.8
**Description:**
`webgme start` gives error.
**Steps to Reproduce:**

`webgme start`

**Results:**
```
webgme start
Installing dependencies...
/home/ubuntu/.nvm/versions/node/v12.19.0/lib/node_modules/webgme-cli/node_modules/npm/node_modules/graceful-fs/polyfills.js:267
      if (cb) cb.apply(this, arguments)
                 ^

TypeError: cb.apply is not a function
    at /home/ubuntu/.nvm/versions/node/v12.19.0/lib/node_modules/webgme-cli/node_modules/npm/node_modules/graceful-fs/polyfills.js:267:18
    at FSReqCallback.oncomplete (fs.js:169:5)

```

**Comment by yogeshVU** [comment]
@brollb  thanks!
